### ISSUE TITLE
Processes are terminated incorrectly

### ISSUE THREAD

**Issue by whymarrh** [kumavis/shell-parallel#2]
When one of the started processes ends, all the other processes are sent `SIGKILL` which doesn't allow them to cleanup after themselves. To give an example, when program `a` (source below) receives [`SIGTERM`](https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html) it will write a file to disk before successfully exiting. When shell-parallel sends `SIGKILL` the program doesn't have the chance to go through that shutdown procedure:

```
$ ./node_modules/.bin/shell-parallel -x './test/programs/a' -x 'sleep 10' -x './test/programs/b'
spawned (73963): "./test/programs/a"
spawned (73964): "sleep 10"
spawned (73965): "./test/programs/b"
exited: "sleep 10"
$ ls was-graceful.log
ls: was-graceful.log: No such file or directory
```

This isn't ideal because a lot of programs will use `SIGTERM` to, for example, cleanly shutdown servers or worker pools, persist some state to disk, or otherwise generally shutdown cleanly.

#### `SIGKILL` _is_ needed at some point

That said, sending `SIGKILL` is correct after some point as it is possible for programs to ignore `SIGTERM` and only sending `SIGTERM` would risk not killing such processes. Program `b` below is an example of one such program. (See also https://github.com/kimmobrunfeldt/concurrently/issues/155, which is an example of what this looks like in practice.)

#### Example programs

`test/programs/a` (correctly responds to `SIGTERM`):

```python
#!/usr/bin/env python -u

from __future__ import print_function
import signal
import sys

def graceful_exit(sig, frame):
    print('GRACEFUL')
    print('GRACEFUL', file=open("was-graceful.log", "wt"))
    sys.exit(0)

signal.signal(signal.SIGINT,  graceful_exit)
signal.signal(signal.SIGTERM, graceful_exit)
signal.pause()
```

`test/programs/b` (incorrectly ignores `SIGTERM`):

```python
#!/usr/bin/env python -u

from __future__ import print_function
import signal
import sys
import time

def ignore_signal(sig, frame):
    print('IGNORING SIGNAL')
    while True:
        time.sleep(42)

signal.signal(signal.SIGINT,  ignore_signal)
signal.signal(signal.SIGTERM, ignore_signal)
signal.pause()
```

#### Possible solution

Based on a bit of research, I think a more correct way to kill child processes would be to send `SIGTERM` to the children (not the the whole trees, just immediate children) and after some timeout send `SIGKILL` to the tree. This is what a few init systems will do.

**Comment by kumavis** [comment]
I decided to deprecate this module and reccommend `concurrently` instead
